### ISSUE TITLE
Iris has updated. Please support its new version, crashes if used as of right now.

### ISSUE THREAD

**Issue by MagmaBro123** [Qendolin/better-clouds#82]
## Description
Title.

### System Environment
- GPU: AMD RX 580.
- Mod Version: better-clouds-1.3.16+1.20.1.
- OS: Windows 10.

*Optional:*
- Shader Pack: 
- Other Mods: 

### Game Log / Crash Report

[crash-2024-04-23_15.13.35-client.txt](https://github.com/Qendolin/better-clouds/files/15083133/crash-2024-04-23_15.13.35-client.txt)

**Comment by Qendolin** [comment]
I don't have time to work on Better Clouds for at least another month but probably much longer. Pull Requests are welcome.

**Comment by memphismc** [comment]
crashes for me too

**Comment by iblowmymind** [comment]
Iris just changed its class names around (net.coderbot -> net.irisshaders), and the crash error indicates that it just can't find the old class name. A simple pull request with the new class names should do the trick (although I'm not sure if they've changed anything that's relevant). I'll see what I can do and make a PR if possible.

**Comment by iblowmymind** [comment]
Hello,
So I've taken some time to inspect the changes made with Iris's latest release, and turns out that Iris also went through a bunch of refactors (internal restructuring), especially on its rendering pipeline, which means more work needs to be done to re-implement Iris support, and that it's most likely beyond my level. (haven't dabbled in Iris development before) Sorry!
I'll still try some stuff to make it work, but I hope you can understand if I can't.
Cheers!

**Comment by iblowmymind** [comment]
Nevermind, got it to work!
There's only a configuration menu issue where trying to open settings crashes the game (due to YACL's new update I believe), but once I get that sorted it should be fully working!

**Comment by iblowmymind** [comment]
Okay, so couldn't find the fix for the config page issue (YACL 3.4.0 apparently introduced a new custom tab API which requires a rewrite to the config page of this mod), but if you use YACL 3.3.1 (or just never open the settings) everything else works. So as much as I'd like to be implement a fix for that too, I'm just going to make a pull request as it's probably beyond me.

**Comment by memphismc** [comment]
on fabric 1.20.1
with yacl 3.4.1
with latest version of better clouds for 1.20.1
with iris 1.7.0

it crashes upon world load, please do let me know when a fix is released, if not then mod menu will probably notify me but until then ill be using a downgraded iris
